### ISSUE TITLE
perl pgsqlms - "Soft" vs "Hard" checks on secondaries

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#10]
Currently, in sub `_confirm_role`, the second, pg_controldata based check ("soft" check) is never done because we never set OCF_CHECK_LEVEL to anything lower than 10.

This sub is only called after `_pg_isready` has confirmed the instance is listening.
Maybe we could only do the "hard" check (is_in_recovery + lsn_diff) when on the primary, in the case of a secondary the controldata check could be enough.
Thus the pg_controldata based check ("soft" check), would be put at the beginning of the sub, and done every time.
It would also be modified not to return if the role found is primary, but continue instead with the "hard" check (is_in_recovery + lsn_diff).

Advantage: we avoid querying secondaries every "monitor_frequency" s.

Risk: if someone does a pg_ctl promote outside from pacemaker, it will not be detected.

**Comment by ioguix** [comment]
I just remove OCF_CHECK_LEVEL with the following patch: b6c162437bc6d4205faa918b72b20f69dc370a4b

For now, it is better to keep the code simple and robust, with no consideration for micro-optimization.

We might want to come back at this subject later, maybe if we consider to support warm standby. But for now, we keep the code simple.
