### ISSUE TITLE
perl pgsqlms - OCF_CHECK_LEVEL usefulness

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#11]
The `OCF_CHECK_LEVEL` variable is supposed to provide a way to distinct between "soft" and "hard" checks during monitor actions.
At this point, we never use it, as it is systematically set to "10" ot higher.

Is there any use case where we would like to relax the CHECK_LEVEL ?
If not, any reference to `OCF_CHECK_LEVEL` should go away.

This variable is currently referenced in subs `_confirm_role`, `confirm_stopped`, and set during `pgsql_start`, pgsql_stop`,`pgsql_monitor`,`pgsql_demote`,`pgsql_promote`.

**Comment by ioguix** [comment]
I just removed this with the following patch: b6c162437bc6d4205faa918b72b20f69dc370a4b

For now, we will leave without this feature for the code simplicity sake.
