### ISSUE TITLE
perl pgsqlms - Immediate PostgreSQL shutdown during resource stop

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#14]
In sub `pgsql_stop`, we currently never force the instance to shut down.
Add a timeout in pg_ctl -m fast call, and immediate stop ??
See http://www.linux-ha.org/doc/dev-guides/_literal_stop_literal_action.html

We probably prefer having a node fencing in case of stop error than a silently corrupted database by switchover using -m immediate.

**Comment by ioguix** [comment]
Hi,

After reading this documentation 2 or 3 times, I finally conclude the current code comply with it. 

The documentation warns that:

> A failed stop operation is a potentially dangerous situation which the cluster manager will almost invariably try to resolve by means of node fencing. In other words, the cluster manager will forcibly evict from the cluster a node on which a stop operation has failed. While this measure serves ultimately to protect data, it does cause disruption to applications and their users.

Possible rewording is: returning an error during the stop operation might impact the service  availability

And it concludes with:

> Thus, a resource agent should make sure that it exits with an error **only** if all avenues for proper resource shutdown have been exhausted.

The current code already try the **only** possible avenue for a proper resource shutdown using `pg_ctl -m fast` and we do not consider the `smart` in the code for this action anyway. So, in my opinion, our current behavior is in accordance with this warning from the RA dev guide: we couldn't stop faster enough using `fast` method so we return an error.

I delete my comment about this in the source code and will close this issue.

Thanks.
