### ISSUE TITLE
perl pgsqlms - Error level when controldata is not consistent with pg_isready

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#15]
In sub `pgsql_monitor`, we raise soft errors (`OCF_ERR_GENERIC`) when we confirm an inconsistency between controldata and pg_isready.
This result probably means that something really wrong is happening.
Should we raise a hard error here instead so the resource goes down immediately ?

**Comment by ioguix** [comment]
pgsqlms moved to its own repo
