### ISSUE TITLE
perl pgsqlms - Pacemaker resource timeout

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#17]
In subs `pgsql_demote` and `pgsql_stop`, we set the pg_ctl stop timeout to ten minutes, in order to let the Pacemaker timeout kick in first.
It would be preferable to get the resource action timeout if possible, so we can be sure we set the timeout to a higher value.

**Comment by ioguix** [comment]
pgsqlms moved to its own repository
