### ISSUE TITLE
perl pgsqlms - Use env vars instead of "crm_node"

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#18]
In sub `pgsql_promote`, instead of `crm_node`, use a resource attribute set during notify using variables available, like `OCF_RESKEY_CRM_meta_notify_slave_uname` and `OCF_RESKEY_CRM_meta_notify_start_uname` ?

**Comment by ioguix** [comment]
pgsqlms moved to its own repo.
