### ISSUE TITLE
perl pgsqlms - Find a better way to avoid promoting the wrong secondary

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#19]
Currently, in sub `pgsql_promote`, if we detect that the selected node to be promoted is not the better candidate, we adapt the master scores accordingly, and break the promotion process, which increases the failcount for the current node.
This is a workaround, we should check if there really is no other way to abort the promotion without raising an error.

Note: probably not possible without changing Pacemaker code itself, cf discussion "problem with master score limited to 1000000" on developers@clusterlabs.org

**Comment by ioguix** [comment]
pgsqlms moved to its own repository
