### ISSUE TITLE
perl pgsqlms - Extend logging possibilities

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#2]
Right now, the RA only write log messages to the local4 syslog facility.
We should probably use env vars to define where to log.

Available variables in Pacemaker: `HA_LOGFACILITY`, `HA_LOGFILE`, `HA_LOGD`, 
`PCMK_debug`, `HA_use_logd`, `HA_logfile`, `HA_logfacility`, `PCMK_use_logd`, 
`HA_DEBUGLOG`, `PCMK_logfile`
(see log funcs in OCF_ROOT/lib/heartbeat/ocf-shellfuncs)

**Comment by ioguix** [comment]
This has been fixed in commit 53ad182d8888.

I ported the functions we are using in a perl module from the officiel ocf-shellfunctions.

ocf_log now uses the same mechanism then its shell equivalent.
