### ISSUE TITLE
Multiple slaves with slow channel and lost master. How to elect right new one?

### ISSUE THREAD

**Issue by ARogovsky** [dalibo/pgsql-resource-agent#22]
Hello, sir!
I have multiple slaves and one master with async replication using your agent.
When master is down, cluster select new one and start it from slave node.
Some slaves have not full replicated from master.
How to elect the right slave as master? This slave will have most high checkpoint (I guess).

**Comment by ioguix** [comment]
Hello,

The pgsqlsr resource agent is not able to find and elect the best slave. It is just not possible considering that it is a stateless resource agent.

Please, see the PAF[1] resource agent, which is able to deal correctly with multiple slaves and elect the best one.

[1] http://dalibo.github.io/PAF/
