### ISSUE TITLE
perl pgsqlms - Avoid systematically updating master score during monitor

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#5]
Currently, in sub `_check_lsn_diff`, we update the master score for every standby node, even if the new value is the same as the previous one.
Would it be meaningful to check the previous value, so we can avoid useless crm conf updates ?

**Comment by ioguix** [comment]
As far as I understand the code of crm_master/crm_attribute and underlying libs, requesting a value only requires some xpath query on the local cib, which sounds quite fast and light.

So I implemented to logic and committed it.
