### ISSUE TITLE
perl pgsqlms - Avoid updating "lsn_diff" parameter during monitor

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#6]
In sub `_check_lsn_diff`, the "lsn_diff" attribute value is set for the standby nodes, but this attribute will only be used during promotion, and its value will be computed again during the "pre-promote", so this step could probably be skipped.

**Comment by ioguix** [comment]
done in f6e024b774608ec4a1b8439f220c464449495e10
