### ISSUE TITLE
perl pgsqlms - Excluding current node during final LSN diff check is useless

### ISSUE THREAD

**Issue by mrimbault** [dalibo/pgsql-resource-agent#8]
In sub `_check_lsn_diff`, when parsing the remaining nodes from partition_nodes after dealing with the ones connected to the primary, we exclude the current node.
The following substition done a few lines before should already have dealt with this case:

```
$partition_nodes =~ s/\s$nodename\s/ /g;
```

In fact, would this substitution have been done before, the same test done in the first partition_nodes parsing could be removed too.

**Comment by ioguix** [comment]
Fixed in latest commit
